apiVersion: v1
kind: Pod
metadata:
  name: miruware
  #k8s에서 생성할 pods의 이름, 하나의 namespace에서는 같은 이름으로 생성 불가능
spec:
  restartPolicy: OnFailure

  volumes:
  - name: pvc-volume  
  #수정 불필요
    persistentVolumeClaim:
       claimName: miruware
     
  containers:
  - name: gpu-container
    image: mw/ub20.04-torch_1.7.1:2021-02-25
    volumeMounts:
    - mountPath: /home/miruware
      name: pvc-volume 
    command:
      - "/bin/sh"
      - "-c"
    args:
      - test test 123123 test test 123123
    securityContext:
      allowPrivilegeEscalation: false

resources:
      requests:
        nvidia.com/gpu: 2
      limits:
        nvidia.com/gpu: 2
