apiVersion: v1
kind: Pod
metadata:
  name: USERNAME
  #k8s에서 생성할 pods의 이름, 하나의 namespace에서는 같은 이름으로 생성 불가능
spec:
  restartPolicy: OnFailure

  volumes:
  - name: shmdir
    emptyDir:
      medium: Memory
  - name: pvc-volume  
  #수정 불필요
    persistentVolumeClaim:
       claimName: CLAIMNAME 
     
  containers:
  - name: gpu-container
    image: IMAGE
    volumeMounts:
    - mountPath: /dev/shm
      name: shmdir
    - mountPath: MOUNTPATH 
      name: pvc-volume 
    command:
      - "/bin/sh"
      - "-c"
    args:
      - COMMANDINPUT
    securityContext:
      allowPrivilegeEscalation: false

    resources:
      requests:
        nvidia.com/gpu: 4
      limits:
        nvidia.com/gpu: 4
